### ISSUE TITLE
Missing Highest Score Label

### ISSUE THREAD

**Issue by Devlopers** [Jeffchiucp/ExplodingPlatForm#11]
As per of user tester, Highest Score Label needs to be added

        setUpHighScoreLabel()

**Comment by Jeffchiucp** [comment]
Added Highest Score Label in the Game

**Comment by Devlopers** [comment]
As per of user tester, user like to see the Highest Score throughout the GamePlay

**Comment by Jeffchiucp** [comment]
- implemented the high score label
- requested the user to test the Highest Score 
- need to see where to put the Highest Score at the end of the Game

**Comment by Jeffchiucp** [comment]
- requested the user to test to test 
![highestscore](https://cloud.githubusercontent.com/assets/10523517/17194974/fb494368-540f-11e6-8c41-03e972d17f56.png)
the Highest Score

**Comment by Jeffchiucp** [comment]
Need users testing on game score

**Comment by Jeffchiucp** [comment]
Finished the HighGameScore

**Comment by Jeffchiucp** [comment]
User Testing approved
