### ISSUE TITLE
Feature Request for new Game Score System

### ISSUE THREAD

**Issue by Devlopers** [Jeffchiucp/ExplodingPlatForm#13]
As per of user tester, Game Score system needs to be more interesting and fun.
It should allow users a greater incentive to capture the items and other special coin objects

**Comment by Jeffchiucp** [comment]
See the Game Design Doc for issue #13

**Comment by Devlopers** [comment]
HighestScore Added but should move to the end of the Screen

**Comment by Jeffchiucp** [comment]
Accepted the feature request

**Comment by Jeffchiucp** [comment]
Requested to reconsider the GamePlan.

**Comment by Jeffchiucp** [comment]
updated the Kunai and game objective
