### ISSUE TITLE
Issue Testing at iPhone 4 and iPhone 5 Simulator

### ISSUE THREAD

**Issue by Devlopers** [Jeffchiucp/ExplodingPlatForm#16]
Beta User Testing: There is crashing Issue when Testing at iPhone 4 and iPhone 5 Simulator. Requested for internal testing on those device like iPhone 5

**Comment by Jeffchiucp** [comment]
User testing requested for these devices or simulator

**Comment by Jeffchiucp** [comment]
App pushed to the store and user testing at Testflight confirmed working on iPhone 4
