### ISSUE TITLE
Game Instruction Needed for Tilting

### ISSUE THREAD

**Issue by Devlopers** [Jeffchiucp/ExplodingPlatForm#17]
Game Instruction Needed for Tilting.  User Tester were confused how to Start the Game. We need good instruction! Instead of Tapping, user needs to Tilt their phone to play the Game.

**Comment by Devlopers** [comment]
The instruction for Tilt can be better. See the user feedback #15

**Comment by Jeffchiucp** [comment]
implemented the background
