### ISSUE TITLE
Peer Review for Cleaner code on GameScene.swift

### ISSUE THREAD

**Issue by Jeffchiucp** [Jeffchiucp/ExplodingPlatForm#18]
Clean up DidMovetoView at GameScene.swift
Create a separate class for Instructions method

**Comment by Jeffchiucp** [comment]
Request for Peer Review for codes @jorgeavelar98 @Devlopers

**Comment by Devlopers** [comment]
Refactoring codes needed for GameScene and PlayerState.
Suggested to implement a Protocol class

**Comment by Devlopers** [comment]
Accepted the plan and implement a Protocol class and refactoring the code

**Comment by Jeffchiucp** [comment]
Also refactor the Code and published the App to TestFlight. Requested for Beta Testing.

**Comment by Jeffchiucp** [comment]
Finished the Protocol implementation
