### ISSUE TITLE
Feature for Heart item for Game Play

### ISSUE THREAD

**Issue by Devlopers** [Jeffchiucp/ExplodingPlatForm#19]
Game Feature Request | Needed for Health Item. User Tester were wondering if there's a way to increase the Health. Please added the health item so player game becomes more interesting

**Comment by Jeffchiucp** [comment]
Feature request accepted. Working on this enhancement feature.

**Comment by Jeffchiucp** [comment]
Figured out the bugs and changed addHeart
`    func addHeart(){
        if _life >= HealthCounter.maxHeartCount {
            return`
So player will not have heart exceed max health allowed

**Comment by Jeffchiucp** [comment]
User Testing rquesting

**Comment by jorgeavelar98** [comment]
You should add a "Tap to Play" label to make it clear to the user so they can know what to do.

**Comment by Jeffchiucp** [comment]
Implemented the feature "ready" "Begin" @jorgeavelar98 
User Testing requested

**Comment by Devlopers** [comment]
Finished user testing. 
One feedback is to make heart more random and not so easy to collect
