### ISSUE TITLE
Feature Request for Kunai Object to match the GamePlay

### ISSUE THREAD

**Issue by Devlopers** [Jeffchiucp/ExplodingPlatForm#20]
User Feedback: Feature Request for Kunai Object to match the GamePlay! 

![kunai](https://cloud.githubusercontent.com/assets/7025757/17346439/87026610-58bf-11e6-9b86-0d9ee52303f3.png)

**Comment by Jeffchiucp** [comment]
added the feature.
Requesting user feedback

**Comment by Jeffchiucp** [comment]
feature implementation complete
