### ISSUE TITLE
Issue with Particle effects for Random Explosion

### ISSUE THREAD

**Issue by Jeffchiucp** [Jeffchiucp/ExplodingPlatForm#3]
There is Issue with Particle effects for Random Explosion.
The Simulator and iPhone Build does not show any particle effects when the player goes to the player State.  Request for code review.

**Comment by Jeffchiucp** [comment]
TrailSmoke file is missing. Request for TrailSmoke.scene for Animation

**Comment by Devlopers** [comment]
Confirmed that TrailSmoke is fixed

**Comment by Devlopers** [comment]
Particle effects for Random Explosion is still missing
![img_0008](https://cloud.githubusercontent.com/assets/7025757/17064423/41b6bcae-4ff1-11e6-8417-1bc86d26cdf1.PNG)

**Comment by Jeffchiucp** [comment]
remove a lot of game art and polished the game node @Devlopers
