### ISSUE TITLE
Feature Request to remove the Health Bar

### ISSUE THREAD

**Issue by Devlopers** [Jeffchiucp/ExplodingPlatForm#6]
Feature Request to remove the Health Bar

**Comment by Jeffchiucp** [comment]
Remove the Health Bar and plan to replace it with Heart for Lives

**Comment by Devlopers** [comment]
User Tester Request to have different Color Effect around the character when the User life is low.  This is another feature request.

**Comment by Jeffchiucp** [comment]
This Feature is done:
- remove the Health Bar
- Add the color change to player when contacting the lava

 request user testing

**Comment by Jeffchiucp** [comment]
-Added the color change to player when contacting the lava. 
user feedback is to add more color around the player.

**Comment by Devlopers** [comment]
Use feedback is to add Health Icons to help the users |

**Comment by Jeffchiucp** [comment]
updated the codes requested for User Testing
