### ISSUE TITLE
User Testing Request: adjust the CoreMotion 

### ISSUE THREAD

**Issue by Jeffchiucp** [Jeffchiucp/ExplodingPlatForm#7]
User Testing Request: adjust the CoreMotion.
I would like to learn more information about CoreMotion adjustment options

**Comment by Devlopers** [comment]
Request accepted to have user testing to reproduce the crashing on iPod or any iOS Device

**Comment by Jeffchiucp** [comment]
Accepted User testing to adjust the CoreMotion sensitivity

**Comment by Jeffchiucp** [comment]
Looking into Apple Documentation for CoreMotion:
https://developer.apple.com/library/ios/documentation/CoreMotion/Reference/CMMotionManager_Class/index.html

Other Documentation: https://www.hackingwithswift.com/example-code/system/how-to-use-core-motion-to-read-accelerometer-data

**Comment by Jeffchiucp** [comment]
Adjusted the Core Motion sensitivity. Requested the user testing: 
For more information about Core Motion, visit Apple's iOS Developer Library: http://apple.co/1F4DjCH. I highly recommend you acquaint yourself with this framework because it's often handy to add accelerometer-based input into your games.
![img_0008](https://cloud.githubusercontent.com/assets/10523517/17119923/f03edcdc-527d-11e6-8905-215d3346071f.PNG)

**Comment by Jeffchiucp** [comment]
-- Increasing the sensitivity. 

   func setupCoreMotion() {
        motionManager.accelerometerUpdateInterval = 0.1
        let queue = NSOperationQueue()
        motionManager.startAccelerometerUpdatesToQueue(queue, withHandler:
            {
                accelerometerData, error in
                guard let accelerometerData = accelerometerData else {
                    return
                }
                let acceleration = accelerometerData.acceleration
                self.xAcceleration = (CGFloat(acceleration.x) * 0.75) +
                    (self.xAcceleration * 0.25)
        })
    }

**Comment by Jeffchiucp** [comment]
User Testing approved
