### ISSUE TITLE
User Testing Request: Crashing occurs to the App

### ISSUE THREAD

**Issue by Jeffchiucp** [Jeffchiucp/ExplodingPlatForm#8]
User Testing Request: Crashing occurs to the App

**Comment by Jeffchiucp** [comment]
Request more User Testing to replicate the problem

**Comment by Devlopers** [comment]
Will have user testing to reproduce the crashing on iPhone device

**Comment by Jeffchiucp** [comment]
I was able to test the App and reproduce the issue.
![screenshot 2016-07-22 10 35 26](https://cloud.githubusercontent.com/assets/10523517/17065968/96d273d8-4ff9-11e6-8f21-43d3f70f8fb8.png)

It turns out to be an assertion failed:

![screenshot 2016-07-22 10 47 22](https://cloud.githubusercontent.com/assets/10523517/17065982/b21829ee-4ff9-11e6-9150-51b65a4920ab.png)

**Comment by Jeffchiucp** [comment]
I changed the line for 489  and update the code. This fixes the assertion failed error:
             switch Int.random(min: 0, max: 4) {

The App seems to be working fine now.  Plan to have more user testing for the App.

**Comment by Jeffchiucp** [comment]
App is working well for the past 10 user testing. I plan to have additional 20 user testing to see the App will crash.

**Comment by Jeffchiucp** [comment]
Close this issue as App is no longer
